version: '3'

tasks:
  clean-build:
    desc: Clean and build the Java project using Maven
    cmds:
      - mvn clean package

  docker-build:
    desc: Build the Docker image with no cache
    cmds:
      - docker build --no-cache -t leanix-mcp:latest .

  docker-run:
    desc: Run the Docker container, exposing port 8080
    cmds:
      - docker run --rm -p 8080:8080 leanix-mcp:latest

  docker-publish:
    desc: Publish the Docker image to a registry (set DOCKER_REGISTRY and IMAGE_NAME env vars)
    cmds:
      - |
        if [ -z "$DOCKER_REGISTRY" ] || [ -z "$IMAGE_NAME" ]; then
          echo "Set DOCKER_REGISTRY and IMAGE_NAME env vars to publish."
          exit 1
        fi
        docker tag leanix-mcp:latest $DOCKER_REGISTRY/$IMAGE_NAME:latest
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
